M48
; DRILL file {KiCad 8.0.0} date 2024-05-11T21:47:55-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-11T21:47:55-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X85.3Y-113.0
X85.3Y-118.0
T2
X106.4Y-55.014
X111.479Y-107.085
X139.42Y-107.086
X154.66Y-56.284
M30
